{% set name = "qrefine" %}
# {% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  # version: {{ version }}
  version:  {{ GIT_DESCRIBE_TAG }}-{{ GIT_DESCRIBE_HASH }}

# add sha256 for releases
source:
  git_url: https://github.com/qrefine/qrefine.git
  # url: https://github.com/qrefine/qrefine/archive/refs/heads/master.tar.gz
  #sha256: a7adc240fd55f74e5f89cdded789b17cd1ab6b0a0ba5ec1f820c0118de2dd847

build:
  osx_is_app: False
  number: 0
  skip: true  # [py<39]
  skip: true # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cctbx
    - python.app      # [osx]
  run:
    - python
    - python.app      # [osx]
    - ase==3.17.0
    - pymongo
    - cctbx
    - networkx
    - xtb
    - mopac

test:
 commands:
   - qr.refine --show-defaults

about:
  home: https://github.com/qrefine/qrefine
  summary: 'Quantum Refinement Module for CCTBX/Phenix'
  description: |
    qrefine is an open-source program that carries out structure refinement (X-ray, Cryo-EM) of
    bio-macromolecules using restraints from quantum chemistry and AI potentials.

  license: Apache-2.0
  license_file: LICENSE.txt
  doc_url: https://qrefine.com/qr.html
  dev_url: https://github.com/qrefine/qrefine

extra:
  recipe-maintainers:
    - hokru
